### ISSUE TITLE
How would it be possible to help with the detection of more models?

### ISSUE THREAD

**Issue by 2haloes** [thinkst/zippy#1]
Hello, 

I saw the post on beehaw.org about this project and started playing around but I've gotten false negatives when using a 7B model. How would it be possible to improve detection so I could try and get more accurate results? And is it possible without lessening detection on larger models such as ChatGPT?

I've gotten the following results using the 7B model: 
Silly generation: Human 0.60
Serious generation: Human 0.039
My own text: Human 0.69

**Comment by ranok** [comment]
The web based UI lets you mark a sample as a false negative. For the python code, I would take some samples and add them to ai-generated.txt which should improve the performance for your model.

**Comment by 2haloes** [comment]
Alright, I believe I can only run the python script on my phone so I wasn't aware, thank you!
