### ISSUE TITLE
Explain what the output number is

### ISSUE THREAD

**Issue by TikoyX** [thinkst/zippy#14]
The output of zippy is for example ('Human', 0.06013429262166636), but what exactly does thew number represent ? What is the range ? Would this be 6% ?

I understand it might make sense for someone deep down in ZipPy but for a person coming and looking for the first time there is no indication anywhere what this number is

**Comment by ranok** [comment]
Thanks for opening this issue, it's a good point to address. I've added a couple paragraphs at the end of the README to hopefully clarify. Please reopen if it's still unclear.
