### ISSUE TITLE
Hello, may I ask if there is a corresponding paper for this code repository? I would like to have a further understanding. Thank you!

### ISSUE THREAD

**Issue by Fluffypp** [thinkst/zippy#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ranok** [comment]
@Fluffypp There is not a published paper, but I did add links to a conference talk and blog with additional information. Let me know if that addresses you needs.
