### ISSUE TITLE
Pipy registration

### ISSUE THREAD

**Issue by g4ze** [thinkst/zippy#9]
**Is your feature request related to a problem? Please describe.**
Hey there! Can we have library of zippy?
**Describe the solution you'd like**
just a clean pip3 install zippy/xyz would be smoother :)

**Describe alternatives you've considered**
none
**Additional context**
Please consider implementing it to https://pypi.org/

**Comment by ranok** [comment]
Thanks for the suggestion @g4ze, we'll work on getting is under the thinkst packages on PyPi.

**Comment by ranok** [comment]
@g4ze You should be able to install it via `pip install thinkst-zippy` (there was another zippy on PyPi), then you can `import zippy` or run `zippy` on the command-line. Thanks to @jayjb the PyPi package will track releases here. Let us know if you have any troubles (I'll update the README shortly).
